name: dvp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.4
  hooks_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  reactive_forms: ^16.1.1
  uuid: ^4.5.1
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1
  reactive_forms_annotations: ^4.3.0
  auto_animated: ^3.2.0
  dio: any
  pretty_dio_logger: ^1.3.1
  lodash_flutter: ^0.0.3
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.3
  flutter_speed_dial: ^7.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.11
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  reactive_forms_generator: ^4.5.2
  go_router_builder: ^2.7.0
  build_verify: ^3.1.0
  flutter_native_splash: ^2.4.1
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.jpg
  android_12:
    image: assets/images/logo.jpg
    icon_background_color: "#000000"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg" # Cambia `image_path_android` y `image_path_ios` por `image_path`
  adaptive_icon_foreground: "assets/images/logo.jpg" # Opcional para íconos adaptativos
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21
